[build]
  command = "npm run build"
  functions = "functions"

[context.production]
  environment = {
    NODE_ENV = "production"
  }

[context.development]
  environment = {
    NODE_ENV = "development"
  }




